name: check

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  verify-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run Roborazzi Verification
        run: ./gradlew verifyRoborazziDebug

      - name: Upload Roborazzi Failure Reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: roborazzi-visual-diffs
          path: '**/build/reports/roborazzi/'
          retention-days: 7
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit_test_report
          path: '**/build/reports/tests/testDebugUnitTest/'

#  ktlint:
#    runs-on: ubuntu-latest
#    timeout-minutes: 5
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - name: Run ktlint
#        run: ./gradlew ktlintCheck
#
#      - name: Upload ktlint report
#        uses: actions/upload-artifact@v4
#        with:
#          name: ktlint.html
#          path: '**/build/reports/ktlint/'
#
#  unit-test:
#    needs: [ ktlint ]
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - name: Run unit tests
#        run: ./gradlew testDebugUnitTest
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: unit_test_report
#          path: '**/build/reports/tests/testDebugUnitTest/'
#
#  instrumentation-test:
#    needs: [ unit-test ]
#    runs-on: ubuntu-latest
#    timeout-minutes: 30
#    steps:
#      - name: Enable KVM group perms
#        run: |
#          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
#          sudo udevadm control --reload-rules
#          sudo udevadm trigger --name-match=kvm
#
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - name: Run instrumentation tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedDebugAndroidTest
#
#      - name: Upload test report
#        uses: actions/upload-artifact@v4
#        with:
#          name: instrumentation_test_report
#          path: '**/build/reports/androidTests/connected/'